import = [
    "~/.config/alacritty/themes/alacritty-theme/themes/catppuccin_mocha.toml"
]

[font]
size = 12

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Normal"

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"
