# general.import = [
#     "~/.config/alacritty/themes/alacritty-theme/themes/catppuccin_mocha.toml"
# ]

# general.import = [
#     "themes/rosepine/dist/rose-pine-dawn.toml",
# ]
[colors.primary]
# foreground = "#000000"
# background = "#ffffff"

[window.dimensions]
lines=50
columns=80

[general]
import = [
    "themes/alacritty-theme/themes/enfocado_light.toml"
]

# [colors.primary]
# background = '#111111'
# foreground = '#CECECE'

[font]
size = 8

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Normal"

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"
